language: php

php:
  - '7.0'
  - '7.1'
  - nightly
  
before_script:
  - composer require php-coveralls/php-coveralls
  - composer install
  - mkdir -p build/logs

script:
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml
  
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - travis_retry php vendor/bin/coveralls -v
